language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - "pip install --upgrade pip wheel"
  - "pip install --use-wheel httpsig"

install:
  - "python setup.py install"

script: "python manage.py test"